name: Linting & Testing
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install the dependencies
        run: yarn

      - name: Run linting
        run: yarn lint

      - name: Run unit tests
        run: yarn test && yarn codecov